In [54]:
import pandas as pd
import numpy as np
import os
import re

In [42]:
quran1_path="C:/Users/Nasser/Desktop/Nase/qran الأعراف.xlsx"
quran2_path="C:/Users/Nasser/Desktop/Nase/qran الأنعام.xlsx"
quran3_path='Quran_Grammar.csv'

In [43]:
quran1=pd.read_excel(quran1_path)
quran2=pd.read_excel(quran2_path)
quran3=pd.read_csv(quran3_path)

In [44]:
quran1

,surah,grammar,verse
0,الأعراف,حروف مقطعة لا محل لها من الإعراب. والله أعلم ب...,المص
1,الأعراف,خبر مرفوع لمبتدإ محذوف تقديره: هذا أو هو. [أو ...,كِتابٌ أُنْزِلَ إِلَيْكَ فَلا يَكُنْ فِي صَدْر...
2,الأعراف,﴿اِتَّبِعُوا﴾: فعل أمر مبني على حذف النون، و(ا...,اِتَّبِعُوا ما أُنْزِلَ إِلَيْكُمْ مِنْ رَبِّك...
3,الأعراف,﴿وَكَمْ﴾ (الواو): استئنافية. (كم): خبرية في مح...,وَكَمْ مِنْ قَرْيَةٍ أَهْلَكْناها فَجاءَها بَأ...
4,الأعراف,﴿فَما﴾ (الفاء): عاطفة. (ما): نافية. ﴿كانَ﴾: فع...,وَكَمْ مِنْ قَرْيَةٍ أَهْلَكْناها فَجاءَها بَأ...
...,...,...,...
201,الأعراف,﴿وَإِخْوانُهُمْ﴾ (الواو): عاطفة [أو استئنافية]...,وَإِخْوانُهُمْ يَمُدُّونَهُمْ فِي الغَيِّ ثُمّ...
202,الأعراف,﴿وَإِذا﴾ (الواو): عاطفة. (إذا): ظرف لما يستقبل...,﴿وَإِذا لَمْ تَأْتِهِمْ بِآيَةٍ قالُوا لَوْلا ...
203,الأعراف,﴿وَإِذا﴾ (الواو): استئنافية. (إذا): سبق إعرابه...,وَإِذا قُرِئَ الْقُرْآنُ فَاسْتَمِعُوا لَهُ وَ...
204,الأعراف,﴿وَاذْكُرْ﴾ (الواو): عاطفة. (اذكر): فعل أمر وا...,وَاُذْكُرْ رَبَّكَ فِي نَفْسِكَ تَضَرُّعًا وَخ...
205,الأعراف,﴿إِنَّ﴾: حرف ناسخ. ﴿الَّذِينَ﴾: اسم موصول اسم ...,إِنَّ الَّذِينَ عِنْدَ رَبِّكَ لا يَسْتَكْبِرُ...

In [45]:
quran2

,surah,grammar,verse
0,الأنعام,﴿الْحَمْدُ﴾ مبتدأ مرفوع. ﴿لِلّهِ﴾ جار ومجرور. ...,الْحَمْدُ لِلّهِ الَّذِي خَلَقَ السَّماواتِ وَ...
1,الأنعام,﴿هُوَ﴾ مبتدأ ﴿الَّذِي﴾ موصول خبر. وجملة: ﴿هُوَ...,NaN
2,الأنعام,﴿وَهُوَ﴾ (الواو) عاطفة (هو) مبتدأ ﴿اللهُ﴾ لفظ ...,وَهُوَ اللهُ فِي السَّماواتِ وَفِي الْأَرْضِ ي...
3,الأنعام,﴿وَما﴾ (الواو) استئنافية. (ما) نافية. ﴿تَأْتِي...,وَما تَأْتِيهِمْ مِنْ آيَةٍ مِنْ آياتِ رَبِّهِ...
4,الأنعام,و(الهاء) مفعول به وجملة: ﴿جاءَهُمْ﴾ في محل جر ...,فَقَدْ كَذَّبُوا بِالْحَقِّ لَمّا جاءَهُمْ فَس...
...,...,...,...
160,الأنعام,﴿قُلْ﴾: فعل أمر، والفاعل مستتر تقديره: أنت، وا...,قُلْ إِنَّنِي هَدانِي رَبِّي إِلى صِراطٍ مُسْت...
161,الأنعام,الإعراب ﴿قُلْ﴾: سبق إعرابها في الآية السابقة. ...,قُلْ إِنَّ صَلاتِي وَنُسُكِي وَمَحْيايَ وَمَما...
162,الأنعام,الإعراب ﴿لا﴾: نافية للجنس. ﴿شَرِيكَ﴾: اسم لا م...,لا شَرِيكَ لَهُ وَبِذلِكَ أُمِرْتُ وَأَنَا أَو...
163,الأنعام,﴿قُلْ﴾: سبق إعرابها في الآية (١٦١). ﴿أَغَيْرَ﴾...,قُلْ أَغَيْرَ اللهِ أَبْغِي رَبًّا وَهُوَ رَبّ...
164,الأنعام,﴿وَهُوَ﴾ (الواو): استئنافية. (هو): مبتدأ. ﴿الّ...,وَهُوَ الَّذِي جَعَلَكُمْ خَلائِفَ الْأَرْضِ و...

In [46]:
quran= pd.concat([quran1,quran2 ], ignore_index=True)

In [47]:
quran

,surah,grammar,verse
0,الأعراف,حروف مقطعة لا محل لها من الإعراب. والله أعلم ب...,المص
1,الأعراف,خبر مرفوع لمبتدإ محذوف تقديره: هذا أو هو. [أو ...,كِتابٌ أُنْزِلَ إِلَيْكَ فَلا يَكُنْ فِي صَدْر...
2,الأعراف,﴿اِتَّبِعُوا﴾: فعل أمر مبني على حذف النون، و(ا...,اِتَّبِعُوا ما أُنْزِلَ إِلَيْكُمْ مِنْ رَبِّك...
3,الأعراف,﴿وَكَمْ﴾ (الواو): استئنافية. (كم): خبرية في مح...,وَكَمْ مِنْ قَرْيَةٍ أَهْلَكْناها فَجاءَها بَأ...
4,الأعراف,﴿فَما﴾ (الفاء): عاطفة. (ما): نافية. ﴿كانَ﴾: فع...,وَكَمْ مِنْ قَرْيَةٍ أَهْلَكْناها فَجاءَها بَأ...
...,...,...,...
366,الأنعام,﴿قُلْ﴾: فعل أمر، والفاعل مستتر تقديره: أنت، وا...,قُلْ إِنَّنِي هَدانِي رَبِّي إِلى صِراطٍ مُسْت...
367,الأنعام,الإعراب ﴿قُلْ﴾: سبق إعرابها في الآية السابقة. ...,قُلْ إِنَّ صَلاتِي وَنُسُكِي وَمَحْيايَ وَمَما...
368,الأنعام,الإعراب ﴿لا﴾: نافية للجنس. ﴿شَرِيكَ﴾: اسم لا م...,لا شَرِيكَ لَهُ وَبِذلِكَ أُمِرْتُ وَأَنَا أَو...
369,الأنعام,﴿قُلْ﴾: سبق إعرابها في الآية (١٦١). ﴿أَغَيْرَ﴾...,قُلْ أَغَيْرَ اللهِ أَبْغِي رَبًّا وَهُوَ رَبّ...
370,الأنعام,﴿وَهُوَ﴾ (الواو): استئنافية. (هو): مبتدأ. ﴿الّ...,وَهُوَ الَّذِي جَعَلَكُمْ خَلائِفَ الْأَرْضِ و...

In [50]:
quran3

,verse,grammar,surah
0,بِسْمِ اللهِ الرَّحْمنِ الرَّحِيمِ,﴿بِسْمِ﴾ جار ومجرور متعلق بفعل محذوف تقديره: أ...,الفاتحة
1,الْحَمْدُ لِلّهِ رَبِّ الْعالَمِينَ,﴿الْحَمْدُ﴾ مبتدأ مرفوع. ﴿لِلّهِ﴾: جار ومجرور ...,الفاتحة
2,الرَّحْمنِ الرَّحِيمِ,﴿الرَّحْمنِ﴾ نعت ثان للفظ الجلالة مجرور.\n﴿الر...,الفاتحة
3,مالِكِ يَوْمِ الدِّينِ,﴿مالِكِ﴾ نعت رابع مجرور. ﴿يَوْمِ﴾: مضاف إليه م...,الفاتحة
4,إِيّاكَ نَعْبُدُ وَإِيّاكَ نَسْتَعِينُ,﴿إِيّاكَ﴾ ضمير مبني في محل نصب مفعول به مقدم.\...,الفاتحة
...,...,...,...
1667,وَالْقَوَاعِدُ مِنَ النِّسَاء اللَّاتِي لَا يَ...,﴿وَالْقَواعِدُ﴾: (الواو): استئنافية. (القواعد...,سورة النور
1668,لَيْسَ عَلَى الْأَعْمَى حَرَجٌ وَلَا عَلَى الْ...,﴿لَيْسَ عَلَى الْأَعْمى حَرَجٌ﴾: مثل (ليس عليك...,سورة النور
1669,إِنَّمَا الْمُؤْمِنُونَ الَّذِينَ آمَنُوا بِال...,﴿إِنَّمَا﴾: كافة ومكفوفة. ﴿الْمُؤْمِنُونَ﴾: مب...,سورة النور
1670,لَا تَجْعَلُوا دُعَاء الرَّسُولِ بَيْنَكُمْ كَ...,﴿لا﴾: ناهية جازمة. ﴿تَجْعَلُوا﴾: فعل مضارع مجز...,سورة النور
1671,أَلَا إِنَّ لِلَّهِ مَا فِي السَّمَاوَاتِ وَال...,﴿أَلا﴾: حرف استفتاح وتنبيه. ﴿إِنَّ﴾: ناسخة ناص...,سورة النور

In [52]:
quran_all= pd.concat([quran3,quran], ignore_index=True)

In [53]:
quran_all

,verse,grammar,surah
0,بِسْمِ اللهِ الرَّحْمنِ الرَّحِيمِ,﴿بِسْمِ﴾ جار ومجرور متعلق بفعل محذوف تقديره: أ...,الفاتحة
1,الْحَمْدُ لِلّهِ رَبِّ الْعالَمِينَ,﴿الْحَمْدُ﴾ مبتدأ مرفوع. ﴿لِلّهِ﴾: جار ومجرور ...,الفاتحة
2,الرَّحْمنِ الرَّحِيمِ,﴿الرَّحْمنِ﴾ نعت ثان للفظ الجلالة مجرور.\n﴿الر...,الفاتحة
3,مالِكِ يَوْمِ الدِّينِ,﴿مالِكِ﴾ نعت رابع مجرور. ﴿يَوْمِ﴾: مضاف إليه م...,الفاتحة
4,إِيّاكَ نَعْبُدُ وَإِيّاكَ نَسْتَعِينُ,﴿إِيّاكَ﴾ ضمير مبني في محل نصب مفعول به مقدم.\...,الفاتحة
...,...,...,...
2038,قُلْ إِنَّنِي هَدانِي رَبِّي إِلى صِراطٍ مُسْت...,﴿قُلْ﴾: فعل أمر، والفاعل مستتر تقديره: أنت، وا...,الأنعام
2039,قُلْ إِنَّ صَلاتِي وَنُسُكِي وَمَحْيايَ وَمَما...,الإعراب ﴿قُلْ﴾: سبق إعرابها في الآية السابقة. ...,الأنعام
2040,لا شَرِيكَ لَهُ وَبِذلِكَ أُمِرْتُ وَأَنَا أَو...,الإعراب ﴿لا﴾: نافية للجنس. ﴿شَرِيكَ﴾: اسم لا م...,الأنعام
2041,قُلْ أَغَيْرَ اللهِ أَبْغِي رَبًّا وَهُوَ رَبّ...,﴿قُلْ﴾: سبق إعرابها في الآية (١٦١). ﴿أَغَيْرَ﴾...,الأنعام
2042,وَهُوَ الَّذِي جَعَلَكُمْ خَلائِفَ الْأَرْضِ و...,﴿وَهُوَ﴾ (الواو): استئنافية. (هو): مبتدأ. ﴿الّ...,الأنعام

In [55]:
def clean_grammar_text(text):
    # Remove any content inside brackets including the brackets themselves
    cleaned_text = re.sub(r'\[.*?\]|\(.*?\)|\{.*?\}', '', text)
    # Remove specific characters "﴾" and "﴿"
    cleaned_text = cleaned_text.replace("﴾", "").replace("﴿", "")
    # Remove extra spaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

In [56]:
quran_all['grammar'] = quran_all['grammar'].apply(clean_grammar_text)

In [57]:
quran_all

,verse,grammar,surah
0,بِسْمِ اللهِ الرَّحْمنِ الرَّحِيمِ,بِسْمِ جار ومجرور متعلق بفعل محذوف تقديره: أبد...,الفاتحة
1,الْحَمْدُ لِلّهِ رَبِّ الْعالَمِينَ,الْحَمْدُ مبتدأ مرفوع. لِلّهِ: جار ومجرور متعل...,الفاتحة
2,الرَّحْمنِ الرَّحِيمِ,الرَّحْمنِ نعت ثان للفظ الجلالة مجرور. الرَّحِ...,الفاتحة
3,مالِكِ يَوْمِ الدِّينِ,مالِكِ نعت رابع مجرور. يَوْمِ: مضاف إليه مجرور...,الفاتحة
4,إِيّاكَ نَعْبُدُ وَإِيّاكَ نَسْتَعِينُ,إِيّاكَ ضمير مبني في محل نصب مفعول به مقدم. نَ...,الفاتحة
...,...,...,...
2038,قُلْ إِنَّنِي هَدانِي رَبِّي إِلى صِراطٍ مُسْت...,قُلْ: فعل أمر، والفاعل مستتر تقديره: أنت، والج...,الأنعام
2039,قُلْ إِنَّ صَلاتِي وَنُسُكِي وَمَحْيايَ وَمَما...,الإعراب قُلْ: سبق إعرابها في الآية السابقة. إِ...,الأنعام
2040,لا شَرِيكَ لَهُ وَبِذلِكَ أُمِرْتُ وَأَنَا أَو...,الإعراب لا: نافية للجنس. شَرِيكَ: اسم لا مبني ...,الأنعام
2041,قُلْ أَغَيْرَ اللهِ أَبْغِي رَبًّا وَهُوَ رَبّ...,قُلْ: سبق إعرابها في الآية . أَغَيْرَ : للاستف...,الأنعام
2042,وَهُوَ الَّذِي جَعَلَكُمْ خَلائِفَ الْأَرْضِ و...,وَهُوَ : استئنافية. : مبتدأ. الَّذِي: اسم موصو...,الأنعام

In [58]:
quran_all.to_csv('Quran_Grammar.csv', index=False)

In [62]:
quran_path='Quran_Grammar.csv'
quran_test=pd.read_csv(quran_path)

In [63]:
quran_test

,verse,grammar,surah
0,بِسْمِ اللهِ الرَّحْمنِ الرَّحِيمِ,بِسْمِ جار ومجرور متعلق بفعل محذوف تقديره: أبد...,الفاتحة
1,الْحَمْدُ لِلّهِ رَبِّ الْعالَمِينَ,الْحَمْدُ مبتدأ مرفوع. لِلّهِ: جار ومجرور متعل...,الفاتحة
2,الرَّحْمنِ الرَّحِيمِ,الرَّحْمنِ نعت ثان للفظ الجلالة مجرور. الرَّحِ...,الفاتحة
3,مالِكِ يَوْمِ الدِّينِ,مالِكِ نعت رابع مجرور. يَوْمِ: مضاف إليه مجرور...,الفاتحة
4,إِيّاكَ نَعْبُدُ وَإِيّاكَ نَسْتَعِينُ,إِيّاكَ ضمير مبني في محل نصب مفعول به مقدم. نَ...,الفاتحة
...,...,...,...
2038,قُلْ إِنَّنِي هَدانِي رَبِّي إِلى صِراطٍ مُسْت...,قُلْ: فعل أمر، والفاعل مستتر تقديره: أنت، والج...,الأنعام
2039,قُلْ إِنَّ صَلاتِي وَنُسُكِي وَمَحْيايَ وَمَما...,الإعراب قُلْ: سبق إعرابها في الآية السابقة. إِ...,الأنعام
2040,لا شَرِيكَ لَهُ وَبِذلِكَ أُمِرْتُ وَأَنَا أَو...,الإعراب لا: نافية للجنس. شَرِيكَ: اسم لا مبني ...,الأنعام
2041,قُلْ أَغَيْرَ اللهِ أَبْغِي رَبًّا وَهُوَ رَبّ...,قُلْ: سبق إعرابها في الآية . أَغَيْرَ : للاستف...,الأنعام
2042,وَهُوَ الَّذِي جَعَلَكُمْ خَلائِفَ الْأَرْضِ و...,وَهُوَ : استئنافية. : مبتدأ. الَّذِي: اسم موصو...,الأنعام